name: Tests

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.19'
      - name: Run linter
        run: make ci-lint
      - name: Run coverage
        run: go test -cover -coverprofile=coverage.txt -count=3 -short
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
